- name: Install ca-certificates
  apt:
    pkg: ca-certificates
    state: present
    update_cache: true
  become: yes

- name: Install curl
  apt:
    pkg: curl
    state: present
    update_cache: true
  become: yes

- name: Install gnupg
  apt:
    pkg: gnupg
    state: present
    update_cache: true
  become: yes

- name: Install lsb-release
  apt:
    pkg: lsb-release
    state: present
    update_cache: true
  become: yes

- name: Add Syncthing GPG apt Key
  apt_key:
    url: https://syncthing.net/release-key.gpg
    state: present

- name: Add Syncthing Repository
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present

- name: Install syncthing
  apt:
    name: syncthing
    state: latest
    update_cache: true

- name: Enable syncthing service
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: syncthing@ubuntu

- ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: '204800'
    state: present
